# Generated by Django 3.1 on 2020-09-25 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_states',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'c_states',
            },
        ),
        migrations.CreateModel(
            name='chats',
            fields=[
                ('chat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.c_states')),
            ],
            options={
                'db_table': 'chats',
            },
        ),
        migrations.CreateModel(
            name='users',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=120)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='u_states',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.users')),
            ],
            options={
                'db_table': 'u_states',
            },
        ),
        migrations.CreateModel(
            name='messages',
            fields=[
                ('message_id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.CharField(blank=True, max_length=4000, null=True)),
                ('date_msj', models.DateTimeField(blank=True, null=True)),
                ('url_file', models.CharField(blank=True, max_length=500, null=True)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.users')),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='chat_users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chats')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.users')),
            ],
            options={
                'db_table': 'chat_users',
            },
        ),
        migrations.CreateModel(
            name='u_friends',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='+', serialize=False, to='chat.users')),
                ('user_added', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chat.users')),
            ],
            options={
                'db_table': 'u_friends',
                'unique_together': {('user', 'user_added')},
            },
        ),
    ]
