# Generated by Django 3.1 on 2020-09-25 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200925_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='users',
            name='username',
            field=models.CharField(default='', max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='users',
            name='usuario_activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='users',
            name='usuario_administrador',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
